apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-module
  labels:
    app: secrets-module
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secrets-module
  template:
    metadata:
      labels:
        app: secrets-module
    spec:
      containers:
      - name: secrets-module
        image: aheshalagu/hello_server
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: $CONTAINER_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-module
spec:
  type: NodePort
  selector:
    app: secrets-module
  ports:
  - port: $K8SPORT
    targetPort: $TARGET_PORT