apiVersion: apps/v1
kind: Deployment
metadata:
  name: sercets-module
  labels:
    app: secrets-modulei
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secrets-module
  template:
    metadata:
      labels:
        app: secrets-module
    spec:
      containers:
      - name: secrets-module
        image: aheshalagu/secrets_management
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-module
spec:
  type: NodePort
  selector:
    app: secrets-module
  ports:
  - port: 3333
    targetPort: 3000