version: '1.0.0'

services:
  express-server:
    image: aheshalagu/hello_server
    environment:
      - PORT=${PORT}
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${PORT}:${PORT}
        